name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build docker image
        run: docker build -t hemantyadavv/ticket-management .

      - name: Publish image to docker hub
        run: docker push hemantyadavv/ticket-management:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull hemantyadavv/ticket-management:latest

      - name: Delete old container
        run: docker rm -f ticket-management-container

      - name: Run Docker container

        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}

        run: docker run -d -p 4000:4000 --name ticket-management-container -e MONGO_URI=`${{ secrets.MONGO_URI }}` hemantyadavv/ticket-management:latest

      - name: Fetch application logs
        run: docker logs ticket-management-container